services:
  c4-config-exporter:
    build:
      context: ../../
      dockerfile: dev_env/dev-c4-config-exporter/Dockerfile
    container_name: dev-c4-config-exporter
    restart: unless-stopped
    network_mode: host
    environment:
      C4_HOST: "192.168.122.200"
      C4_PORT: "444"
      C4_USER: "admin"
      C4_PASSWORD: "AsdfgTrewq1@"
      C4_API_PORT: "8001"
    volumes:
      - ./output:/opt/output
