# Generated by Django 5.2.12 on 2026-03-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.CharField(max_length=512)),
                ('gateway_name', models.CharField(blank=True, max_length=255)),
                ('objects_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=512)),
                ('subject_full', models.TextField(blank=True)),
                ('issuer', models.CharField(blank=True, max_length=512)),
                ('role', models.CharField(blank=True, max_length=32)),
                ('is_ca', models.BooleanField(default=False)),
                ('startdate', models.CharField(blank=True, max_length=64)),
                ('enddate', models.CharField(blank=True, max_length=64)),
                ('gosttype', models.CharField(blank=True, max_length=32)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
        ),
        migrations.CreateModel(
            name='AppException',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('vendor_id', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=128)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('password_auth', models.BooleanField(default=True)),
                ('cert_auth', models.BooleanField(default=False)),
                ('password_expired_date', models.CharField(blank=True, max_length=64)),
                ('created_at', models.CharField(blank=True, max_length=64)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
        ),
        migrations.CreateModel(
            name='DDoSProtection',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('mode', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(blank=True, max_length=32)),
                ('blocking_time', models.IntegerField(default=0)),
                ('clear_stats', models.BooleanField(default=False)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
        ),
        migrations.CreateModel(
            name='DDoSRule',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('attack_type', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
            options={
                'ordering': ['attack_type'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('clid', models.CharField(blank=True, max_length=64)),
                ('domain_level', models.IntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('rule_action', models.CharField(max_length=32)),
                ('logging', models.BooleanField(default=False)),
                ('passips', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('is_inverse_src', models.BooleanField(default=False)),
                ('is_inverse_dst', models.BooleanField(default=False)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hwserial', models.CharField(max_length=64)),
                ('platform_version', models.CharField(blank=True, max_length=128)),
                ('platform_name', models.CharField(blank=True, max_length=128)),
                ('timezone_name', models.CharField(blank=True, max_length=128)),
                ('mode', models.CharField(blank=True, max_length=64)),
                ('dhcp_status', models.CharField(blank=True, max_length=32)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('revision', models.IntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('mtu', models.IntegerField(default=1500)),
                ('usage', models.CharField(blank=True, max_length=64)),
                ('addresses', models.JSONField(default=list)),
                ('permitted_protocols', models.JSONField(default=list)),
                ('anti_spoofing', models.BooleanField(default=False)),
                ('clear_df_bit', models.BooleanField(default=False)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('min_length', models.IntegerField(default=0)),
                ('diff', models.IntegerField(default=0)),
                ('passwords_diff', models.IntegerField(default=0)),
                ('low_credit', models.IntegerField(default=0)),
                ('up_credit', models.IntegerField(default=0)),
                ('dig_credit', models.IntegerField(default=0)),
                ('oth_credit', models.IntegerField(default=0)),
                ('expired_days', models.IntegerField(default=0)),
                ('expired_notification_days', models.IntegerField(default=0)),
                ('blocked_days', models.IntegerField(default=0)),
                ('wrong_try_count', models.IntegerField(default=0)),
                ('wrong_try_block', models.IntegerField(default=0)),
                ('dictionary_check', models.BooleanField(default=False)),
                ('domain_level', models.IntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
            options={
                'ordering': ['component_type'],
            },
        ),
        migrations.CreateModel(
            name='StaticRoute',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('dst_ip', models.CharField(blank=True, max_length=64)),
                ('nexthop', models.CharField(blank=True, max_length=64)),
                ('metric', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
        ),
        migrations.CreateModel(
            name='VPNConfig',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('vpn_type', models.CharField(max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('session_breakup', models.BooleanField(default=False)),
                ('is_log_tunnel_status', models.BooleanField(default=False)),
                ('dynamic_records_lifetime', models.IntegerField(default=0)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
        ),
    ]
