# Generated by Django 5.2.12 on 2026-03-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='lastmodified',
            field=models.BigIntegerField(default=0),
        ),
    ]
