# Generated by Django 5.2.12 on 2026-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_passwordpolicy_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='revision',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
