# Generated by Django 5.2.12 on 2026-03-20 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_gateway_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkObject',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('subtype', models.CharField(blank=True, max_length=32)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='destination_objects',
            field=models.ManyToManyField(blank=True, related_name='fw_rules_as_dst', to='dashboard.networkobject'),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='source_objects',
            field=models.ManyToManyField(blank=True, related_name='fw_rules_as_src', to='dashboard.networkobject'),
        ),
    ]
