# Generated by Django 5.2.12 on 2026-03-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_networkobject_firewallrule_destination_objects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectGroup',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subtype', models.CharField(blank=True, max_length=32)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='dashboard.networkobject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='destination_groups',
            field=models.ManyToManyField(blank=True, related_name='fw_rules_as_dst', to='dashboard.objectgroup'),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='source_groups',
            field=models.ManyToManyField(blank=True, related_name='fw_rules_as_src', to='dashboard.objectgroup'),
        ),
        migrations.CreateModel(
            name='ServiceObject',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('proto', models.IntegerField(default=0)),
                ('src_port', models.CharField(blank=True, max_length=64)),
                ('dst_port', models.CharField(blank=True, max_length=64)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='fw_rules', to='dashboard.serviceobject'),
        ),
    ]
