# Generated by Django 5.2.12 on 2026-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_objectgroup_firewallrule_destination_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusDbSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.CharField(default='5432', max_length=10)),
                ('dbname', models.CharField(default='cus-logs', max_length=128)),
                ('user', models.CharField(default='monitoring', max_length=128)),
                ('password', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'CUS Database Settings',
            },
        ),
    ]
