# Generated by Django 5.2.12 on 2026-03-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_cusdbsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='install_on',
            field=models.ManyToManyField(blank=True, related_name='fw_rules_installed', to='dashboard.gateway'),
        ),
    ]
