# Generated by Django 5.2.12 on 2026-03-22 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_firewallrule_install_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('domain_level', models.IntegerField(default=0)),
                ('lastmodified', models.BigIntegerField(default=0)),
                ('config_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.configimport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='fw_rules', to='dashboard.application'),
        ),
    ]
