# Generated by Django 5.2.12 on 2026-03-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_application_firewallrule_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.IntegerField(default=7)),
                ('batch_size', models.IntegerField(default=10000)),
                ('tables', models.JSONField(default=list)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cleanup Settings',
            },
        ),
    ]
