# Generated by Django 5.2.12 on 2026-03-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_cleanupsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanupsettings',
            name='interval_seconds',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='cleanupsettings',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
