# Generated by Django 5.2.12 on 2026-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_cleanupsettings_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='position',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='rule_action',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='hwserial',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='networkobject',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='networkobject',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='networkobject',
            name='subtype',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='objectgroup',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceobject',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceobject',
            name='proto',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
