server {
    listen 9003;
    root /exports;

    location ~ ^/exports/([a-zA-Z0-9_\-\.]+)$ {
        try_files /$1 =404;
        add_header Content-Disposition 'attachment';
    }

    location / {
        return 404;
    }
}
