from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.dashboard_view, name='dashboard'),
    path('network/interfaces/', views.interfaces_view, name='interfaces'),
    path('network/routes/', views.routes_view, name='routes'),
    path('network/services/', views.services_view, name='services'),
    path('network/objects/', views.network_objects_view, name='network_objects'),
    path('policy/services/', views.service_objects_view, name='service_objects'),
    path('policy/applications/', views.applications_view, name='applications'),
    path('firewall/rules/', views.firewall_rules_view, name='firewall_rules'),
    path('security/ddos/', views.ddos_view, name='ddos'),
    path('security/app-exceptions/', views.app_exceptions_view, name='app_exceptions'),
    path('vpn/', views.vpn_view, name='vpn'),
    path('certificates/', views.certificates_view, name='certificates'),
    path('system/admins/', views.admins_view, name='admins'),
    path('system/password-policy/', views.password_policy_view, name='password_policy'),
    path('configuration/', views.config_view, name='configuration'),
    path('import/', views.config_view, name='import_config'),
    path('api/export-configs/', views.export_configs_api, name='export_configs'),
    path('sync/', views.sync_from_c4_view, name='sync_from_c4'),
    path('api/sync-list/', views.sync_list_gateways_api, name='sync_list_gateways'),
    path('api/sync-gateway/', views.sync_gateway_api, name='sync_gateway'),
    path('api/rule-counters/', views.rule_counters_api, name='rule_counters_api'),
    path('api/logs/', views.logs_api, name='logs_api'),
    path('monitor/logs/', views.logs_view, name='logs'),
    path('system/maintenance/', views.maintenance_view, name='maintenance'),
    path('system/clear-db/', views.clear_db_view, name='clear_db'),
    path('system/save-cus-db/', views.save_cus_db_view, name='save_cus_db'),
    path('api/test-cus-db/', views.test_cus_db_api, name='test_cus_db'),
    path('api/cus-db-tables/', views.cus_db_tables_api, name='cus_db_tables'),
    path('api/cus-db-cleanup/', views.cus_db_cleanup_api, name='cus_db_cleanup'),
    path('api/cus-db-indexes/', views.cus_db_indexes_api, name='cus_db_indexes'),
    path('api/cus-db-create-indexes/', views.cus_db_create_indexes_api, name='cus_db_create_indexes'),
    path('system/save-cleanup/', views.save_cleanup_settings_view, name='save_cleanup'),
    path('api/run-cleanup/', views.run_cleanup_api, name='run_cleanup'),
]
